//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StopWords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StopWords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreLibrary.Resources.StopWords", typeof(StopWords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///about
        ///above
        ///actually
        ///after
        ///again
        ///against
        ///all
        ///almost
        ///also
        ///although
        ///always
        ///am
        ///an
        ///and
        ///any
        ///are
        ///as
        ///at
        ///be
        ///became
        ///become
        ///because
        ///been
        ///before
        ///being
        ///below
        ///between
        ///both
        ///but
        ///by
        ///can
        ///could
        ///did
        ///do
        ///does
        ///doing
        ///down
        ///during
        ///each
        ///either
        ///else
        ///few
        ///for
        ///from
        ///further
        ///had
        ///has
        ///have
        ///having
        ///he
        ///he&apos;d
        ///he&apos;ll
        ///hence
        ///he&apos;s
        ///her
        ///here
        ///here&apos;s
        ///hers
        ///herself
        ///him
        ///himself
        ///his
        ///how
        ///how&apos;s
        ///I
        ///I&apos;d
        ///I&apos;ll
        ///I&apos;m
        ///I&apos;ve
        ///if
        ///in
        ///into
        ///is
        ///it
        ///it&apos;s
        ///its
        ///itself
        ///just
        ///let&apos;s
        ///may
        ///maybe
        ///me
        ///might        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StopWordList {
            get {
                return ResourceManager.GetString("StopWordList", resourceCulture);
            }
        }
    }
}
